### ISSUE TITLE
一个代码错误

### ISSUE THREAD

**Issue by Bowen1911** [zhan3333/python-Cellular-automata#1]
https://github.com/zhan3333/python-Cellular-automata/blob/b2903586f484c7725030f4eb8a501ca4c8edd4a4/box_control.py#L53

这一行写错了，应该是 `if boxs[0][y-1]['value'] == 1` 表示左下的格子

除此之外没发现别的代码问题，但是逻辑方面有个疑问，这里的更新网格状态的时候，比如第一个元胞更新了，直接在原本的状态里面修改了它的状态，在遍历别的元胞的时候，其他的元胞会受到之前更新的元胞的影响，个人认为是不是应该创建一个当前状态的副本，更新状态的时候参考这个副本，修改值的时候直接改原本的值就行

**Comment by zhan3333** [comment]
> https://github.com/zhan3333/python-Cellular-automata/blob/b2903586f484c7725030f4eb8a501ca4c8edd4a4/box_control.py#L53
> 
> 这一行写错了，应该是 `if boxs[0][y-1]['value'] == 1` 表示左下的格子
> 
> 除此之外没发现别的代码问题，但是逻辑方面有个疑问，这里的更新网格状态的时候，比如第一个元胞更新了，直接在原本的状态里面修改了它的状态，在遍历别的元胞的时候，其他的元胞会受到之前更新的元胞的影响，个人认为是不是应该创建一个当前状态的副本，更新状态的时候参考这个副本，修改值的时候直接改原本的值就行

看起来确实错误了一行，更新状态逻辑如你所说应该用副本来判断更新，不然会受到已更新单元值的影响。你可以 pull request 吗？或者等我有空更新

**Comment by zhan3333** [comment]
Fixed #3
